// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMHzM1JANW7P-kZmmLITp3SDeX7Hf4BoY',
    appId: '1:163653737979:web:d81a882976dbe7ec447f5e',
    messagingSenderId: '163653737979',
    projectId: 'rdp-to-do-list-bdb17',
    authDomain: 'rdp-to-do-list-bdb17.firebaseapp.com',
    storageBucket: 'rdp-to-do-list-bdb17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD0arLUU2JxLJSIs3sxWcEDVsyrEbvbDg',
    appId: '1:163653737979:android:2bc8029c6758dd60447f5e',
    messagingSenderId: '163653737979',
    projectId: 'rdp-to-do-list-bdb17',
    storageBucket: 'rdp-to-do-list-bdb17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvZ9ff0P5pqjLl3klP56v87hJRX6FwEyc',
    appId: '1:163653737979:ios:65ba8ff8b7a84c23447f5e',
    messagingSenderId: '163653737979',
    projectId: 'rdp-to-do-list-bdb17',
    storageBucket: 'rdp-to-do-list-bdb17.appspot.com',
    iosBundleId: 'com.example.rdpTodolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvZ9ff0P5pqjLl3klP56v87hJRX6FwEyc',
    appId: '1:163653737979:ios:65ba8ff8b7a84c23447f5e',
    messagingSenderId: '163653737979',
    projectId: 'rdp-to-do-list-bdb17',
    storageBucket: 'rdp-to-do-list-bdb17.appspot.com',
    iosBundleId: 'com.example.rdpTodolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMHzM1JANW7P-kZmmLITp3SDeX7Hf4BoY',
    appId: '1:163653737979:web:cc98c325fc325af6447f5e',
    messagingSenderId: '163653737979',
    projectId: 'rdp-to-do-list-bdb17',
    authDomain: 'rdp-to-do-list-bdb17.firebaseapp.com',
    storageBucket: 'rdp-to-do-list-bdb17.appspot.com',
  );
}
